### ISSUE TITLE
TypeError: witbot.hears is not a function

### ISSUE THREAD

**Issue by anderskitson** [mbrevoort/witbot-sample#2]
Hi, Mike. Wasn't sure the best place to ask about this. I am getting the following error.
I copied and pasted your code, and it doesn't seem to work, I am runing

`WIT_TOKEN=MKOOZ... SLACK_TOKEN=xoxb-2... npm start`

from terminal, am I doing something wrong. Has witbot changed it's API?

```
TypeError: witbot.hears is not a function
    at Object.<anonymous> (/Users/anderskitson/sites/EisenBot/index.js:57:8)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by gvkhirwadkar** [comment]
Yes I am getting the same error.Its too to ask late but have you got the solution.

**Comment by neophytes08** [comment]
hi, i am getting the same problem. Any solution so far?
